--liquibase formatted sql

--changeset wordapp:words-pepg3t1
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'name', '名字', '/neɪm/', 1, 1 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'Miss', '小姐', '/mɪs/', 1, 2 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'boy', '男孩', '/bɔɪ/', 1, 3 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'girl', '女孩', '/ɡɜːl/', 1, 4 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'Mr', '先生', '/ˈmɪstə/', 1, 5 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'eraser', '橡皮', '/ɪˈreɪzə/', 2, 6 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'crayon', '蜡笔', '/ˈkreɪən/', 2, 7 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'sharpener', '卷笔刀', '/ˈʃɑːpənə/', 2, 8 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'pencil-case', '铅笔盒', '/ˈpenslˌkeɪs/', 2, 9 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'white', '白色', '/waɪt/', 3, 10 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'black', '黑色', '/blæk/', 3, 11 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'pink', '粉色', '/pɪŋk/', 3, 12 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'purple', '紫色', '/ˈpɜːpl/', 3, 13 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'brown', '棕色', '/braʊn/', 3, 14 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'bird', '鸟', '/bɜːd/', 4, 15 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'squirrel', '松鼠', '/ˈskwɪrəl/', 4, 16 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'mouse', '老鼠', '/maʊs/', 4, 17 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'cake', '蛋糕', '/keɪk/', 5, 18 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'juice', '果汁', '/dʒuːs/', 5, 19 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'Coke', '可乐', '/kəʊk/', 5, 20 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'hamburger', '汉堡包', '/ˈhæmbɜːɡə/', 5, 21 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'hot dog', '热狗', '/ˌhɒt ˈdɒɡ/', 5, 22 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'chicken', '鸡肉', '/ˈtʃɪkɪn/', 5, 23 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'French fries', '薯条', '/ˌfrentʃ ˈfraɪz/', 5, 24 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'eleven', '十一', '/ɪˈlevn/', 6, 25 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'twelve', '十二', '/twelv/', 6, 26 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'thirteen', '十三', '/ˌθɜːˈtiːn/', 6, 27 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'fourteen', '十四', '/ˌfɔːˈtiːn/', 6, 28 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'fifteen', '十五', '/ˌfɪfˈtiːn/', 6, 29 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'sixteen', '十六', '/ˌsɪksˈtiːn/', 6, 30 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'seventeen', '十七', '/ˌsevnˈtiːn/', 6, 31 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'eighteen', '十八', '/ˌeɪˈtiːn/', 6, 32 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'nineteen', '十九', '/ˌnaɪnˈtiːn/', 6, 33 FROM textbook WHERE code='PEP-G3-T1' UNION ALL
SELECT id, 'twenty', '二十', '/ˈtwenti/', 6, 34 FROM textbook WHERE code='PEP-G3-T1';

--changeset wordapp:words-pepg3t2
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'father', '父亲', '/ˈfɑːðə/', 1, 1 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'mother', '母亲', '/ˈmʌðə/', 1, 2 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'man', '男人', '/mæn/', 1, 3 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'woman', '女人', '/ˈwʊmən/', 1, 4 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'grandfather', '祖父', '/ˈɡrænˌfɑːðə/', 1, 5 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'grandmother', '祖母', '/ˈɡrænˌmʌðə/', 1, 6 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'family', '家庭', '/ˈfæməli/', 1, 7 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'kite', '风筝', '/kaɪt/', 2, 8 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'ball', '球', '/bɔːl/', 2, 9 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'balloon', '气球', '/bəˈluːn/', 2, 10 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'doll', '洋娃娃', '/dɒl/', 2, 11 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'boat', '小船', '/bəʊt/', 2, 12 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'watermelon', '西瓜', '/ˈwɔːtəˌmelən/', 3, 13 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'strawberry', '草莓', '/ˈstrɔːbəri/', 3, 14 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'grape', '葡萄', '/ɡreɪp/', 3, 15 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'peach', '桃', '/piːtʃ/', 3, 16 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'how many', '多少', '/haʊ ˈmeni/', 4, 17 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'twenty-one', '二十一', '/ˌtwenti ˈwʌn/', 4, 18 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'thirty', '三十', '/ˈθɜːti/', 4, 19 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'forty', '四十', '/ˈfɔːti/', 4, 20 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'fifty', '五十', '/ˈfɪfti/', 4, 21 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'sixty', '六十', '/ˈsɪksti/', 4, 22 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'seventy', '七十', '/ˈsevnti/', 4, 23 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'eighty', '八十', '/ˈeɪti/', 4, 24 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'ninety', '九十', '/ˈnaɪnti/', 4, 25 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'one hundred', '一百', '/wʌn ˈhʌndrəd/', 4, 26 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'dragonfly', '蜻蜓', '/ˈdræɡənflaɪ/', 5, 27 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'butterfly', '蝴蝶', '/ˈbʌtəflaɪ/', 5, 28 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'bee', '蜜蜂', '/biː/', 5, 29 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'ant', '蚂蚁', '/ænt/', 5, 30 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'spider', '蜘蛛', '/ˈspaɪdə/', 5, 31 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'walk', '走', '/wɔːk/', 6, 32 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'jump', '跳', '/dʒʌmp/', 6, 33 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'run', '跑', '/rʌn/', 6, 34 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'fly', '飞', '/flaɪ/', 6, 35 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'swim', '游泳', '/swɪm/', 6, 36 FROM textbook WHERE code='PEP-G3-T2' UNION ALL
SELECT id, 'climb', '爬', '/klaɪm/', 6, 37 FROM textbook WHERE code='PEP-G3-T2';

--changeset wordapp:words-pepg4t1
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'window', '窗户', '/ˈwɪndəʊ/', 1, 1 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'board', '写字板', '/bɔːd/', 1, 2 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'light', '灯', '/laɪt/', 1, 3 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'picture', '图画', '/ˈpɪktʃə/', 1, 4 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'door', '门', '/dɔː/', 1, 5 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'floor', '地板', '/flɔː/', 1, 6 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'English', '英语', '/ˈɪŋɡlɪʃ/', 1, 7 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'bedroom', '卧室', '/ˈbedruːm/', 2, 8 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'living room', '客厅', '/ˈlɪvɪŋ ruːm/', 2, 9 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'study', '书房', '/ˈstʌdi/', 2, 10 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'kitchen', '厨房', '/ˈkɪtʃɪn/', 2, 11 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'bathroom', '浴室', '/ˈbɑːθruːm/', 2, 12 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'bed', '床', '/bed/', 2, 13 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'phone', '电话', '/fəʊn/', 2, 14 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'sofa', '沙发', '/ˈsəʊfə/', 2, 15 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'fridge', '冰箱', '/frɪdʒ/', 2, 16 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'table', '桌子', '/ˈteɪbl/', 2, 17 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'uncle', '叔叔/舅舅', '/ˈʌŋkl/', 3, 18 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'aunt', '阿姨/姑姑', '/ɑːnt/', 3, 19 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'baby', '婴儿', '/ˈbeɪbi/', 3, 20 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'cousin', '堂兄弟姐妹', '/ˈkʌzn/', 3, 21 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'doctor', '医生', '/ˈdɒktə/', 3, 22 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'nurse', '护士', '/nɜːs/', 3, 23 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'driver', '司机', '/ˈdraɪvə/', 3, 24 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'farmer', '农民', '/ˈfɑːmə/', 3, 25 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'beef', '牛肉', '/biːf/', 4, 26 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'soup', '汤', '/suːp/', 4, 27 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'vegetable', '蔬菜', '/ˈvedʒtəbl/', 4, 28 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'fruit', '水果', '/fruːt/', 4, 29 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'dinner', '晚餐', '/ˈdɪnə/', 4, 30 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'glasses', '眼镜', '/ˈɡlɑːsɪz/', 5, 31 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'jacket', '夹克衫', '/ˈdʒækɪt/', 5, 32 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 't-shirt', 'T恤', '/ˈtiː ʃɜːt/', 5, 33 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'sweater', '毛衣', '/ˈswetə/', 5, 34 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'shirt', '衬衫', '/ʃɜːt/', 5, 35 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'skirt', '短裙', '/skɜːt/', 5, 36 FROM textbook WHERE code='PEP-G4-T1' UNION ALL
SELECT id, 'dress', '连衣裙', '/dres/', 5, 37 FROM textbook WHERE code='PEP-G4-T1';

--changeset wordapp:words-pepg4t2
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'playground', '操场', '/ˈpleɪɡraʊnd/', 1, 1 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'garden', '花园', '/ˈɡɑːdn/', 1, 2 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'library', '图书馆', '/ˈlaɪbrəri/', 1, 3 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'canteen', '食堂', '/kænˈtiːn/', 1, 4 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'art room', '美术教室', '/ɑːt ruːm/', 1, 5 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'music room', '音乐教室', '/ˈmjuːzɪk ruːm/', 1, 6 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'computer room', '电脑教室', '/kəmˈpjuːtə ruːm/', 1, 7 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'TV room', '电视房', '/ˌtiː ˈviː ruːm/', 1, 8 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'breakfast', '早餐', '/ˈbrekfəst/', 2, 9 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'lunch', '午餐', '/lʌntʃ/', 2, 10 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'English class', '英语课', '/ˈɪŋɡlɪʃ klɑːs/', 2, 11 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'music class', '音乐课', '/ˈmjuːzɪk klɑːs/', 2, 12 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'PE class', '体育课', '/ˌpiː ˈiː klɑːs/', 2, 13 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'o''clock', '点钟', '/əˈklɒk/', 2, 14 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'cloudy', '多云的', '/ˈklaʊdi/', 3, 15 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'sunny', '晴朗的', '/ˈsʌni/', 3, 16 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'rainy', '下雨的', '/ˈreɪni/', 3, 17 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'snowy', '下雪的', '/ˈsnəʊi/', 3, 18 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'windy', '刮风的', '/ˈwɪndi/', 3, 19 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'horse', '马', '/hɔːs/', 4, 20 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'cow', '奶牛', '/kaʊ/', 4, 21 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'sheep', '绵羊', '/ʃiːp/', 4, 22 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'hen', '母鸡', '/hen/', 4, 23 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'goat', '山羊', '/ɡəʊt/', 4, 24 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'socks', '袜子', '/sɒks/', 5, 25 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'shoes', '鞋', '/ʃuːz/', 5, 26 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'shorts', '短裤', '/ʃɔːts/', 5, 27 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'jeans', '牛仔裤', '/dʒiːnz/', 5, 28 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'pants', '长裤', '/pænts/', 5, 29 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'yuan', '元', '/juːˈæn/', 6, 30 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'cheap', '便宜的', '/tʃiːp/', 6, 31 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'expensive', '昂贵的', '/ɪkˈspensɪv/', 6, 32 FROM textbook WHERE code='PEP-G4-T2' UNION ALL
SELECT id, 'pretty', '漂亮的', '/ˈprɪti/', 6, 33 FROM textbook WHERE code='PEP-G4-T2';
