--liquibase formatted sql

--changeset wordapp:words-pepg5t1
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'young', '年轻的', '/jʌŋ/', 1, 1 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'funny', '滑稽的', '/ˈfʌni/', 1, 2 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'kind', '和蔼的', '/kaɪnd/', 1, 3 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'strict', '严格的', '/strɪkt/', 1, 4 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'polite', '有礼貌的', '/pəˈlaɪt/', 1, 5 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'hard-working', '辛勤的', '/ˌhɑːd ˈwɜːkɪŋ/', 1, 6 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'helpful', '乐于助人的', '/ˈhelpfl/', 1, 7 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'clever', '聪明的', '/ˈklevə/', 1, 8 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'shy', '害羞的', '/ʃaɪ/', 1, 9 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Monday', '星期一', '/ˈmʌndeɪ/', 2, 10 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Tuesday', '星期二', '/ˈtjuːzdeɪ/', 2, 11 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Wednesday', '星期三', '/ˈwenzdeɪ/', 2, 12 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Thursday', '星期四', '/ˈθɜːzdeɪ/', 2, 13 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Friday', '星期五', '/ˈfraɪdeɪ/', 2, 14 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Saturday', '星期六', '/ˈsætədeɪ/', 2, 15 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'Sunday', '星期日', '/ˈsʌndeɪ/', 2, 16 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'weekend', '周末', '/ˌwiːkˈend/', 2, 17 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'sandwich', '三明治', '/ˈsænwɪdʒ/', 3, 18 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'salad', '沙拉', '/ˈsæləd/', 3, 19 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'ice cream', '冰淇淋', '/ˈaɪs kriːm/', 3, 20 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'tea', '茶', '/tiː/', 3, 21 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'fresh', '新鲜的', '/freʃ/', 3, 22 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'healthy', '健康的', '/ˈhelθi/', 3, 23 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'delicious', '美味的', '/dɪˈlɪʃəs/', 3, 24 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'empty', '倒空', '/ˈempti/', 4, 25 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'dirty', '脏的', '/ˈdɜːti/', 4, 26 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'sweep', '扫', '/swiːp/', 4, 27 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'clean', '打扫', '/kliːn/', 4, 28 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'wash', '洗', '/wɒʃ/', 4, 29 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'cook', '做饭', '/kʊk/', 4, 30 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'lake', '湖', '/leɪk/', 5, 31 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'forest', '森林', '/ˈfɒrɪst/', 5, 32 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'path', '小路', '/pɑːθ/', 5, 33 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'mountain', '山', '/ˈmaʊntən/', 5, 34 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'river', '河', '/ˈrɪvə/', 5, 35 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'bridge', '桥', '/brɪdʒ/', 5, 36 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'tree', '树', '/triː/', 5, 37 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'village', '村庄', '/ˈvɪlɪdʒ/', 5, 38 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'house', '房子', '/haʊs/', 5, 39 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'flower', '花', '/ˈflaʊə/', 5, 40 FROM textbook WHERE code='PEP-G5-T1' UNION ALL
SELECT id, 'grass', '草地', '/ɡrɑːs/', 5, 41 FROM textbook WHERE code='PEP-G5-T1';

--changeset wordapp:words-pepg5t2
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'January', '一月', '/ˈdʒænjuəri/', 1, 1 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'February', '二月', '/ˈfebruəri/', 1, 2 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'March', '三月', '/mɑːtʃ/', 1, 3 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'April', '四月', '/ˈeɪprəl/', 1, 4 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'May', '五月', '/meɪ/', 1, 5 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'June', '六月', '/dʒuːn/', 1, 6 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'July', '七月', '/dʒuˈlaɪ/', 1, 7 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'August', '八月', '/ɔːˈɡʌst/', 1, 8 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'September', '九月', '/sepˈtembə/', 1, 9 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'October', '十月', '/ɒkˈtəʊbə/', 1, 10 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'November', '十一月', '/nəʊˈvembə/', 1, 11 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'December', '十二月', '/dɪˈsembə/', 1, 12 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'first', '第一', '/fɜːst/', 2, 13 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'second', '第二', '/ˈsekənd/', 2, 14 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'third', '第三', '/θɜːd/', 2, 15 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'fourth', '第四', '/fɔːθ/', 2, 16 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'fifth', '第五', '/fɪfθ/', 2, 17 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'draw pictures', '画画', '/drɔː ˈpɪktʃəz/', 3, 18 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'cook dinner', '做饭', '/kʊk ˈdɪnə/', 3, 19 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'read', '读', '/riːd/', 3, 20 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'climb mountains', '爬山', '/klaɪm ˈmaʊntənz/', 3, 21 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'go shopping', '购物', '/ɡəʊ ˈʃɒpɪŋ/', 3, 22 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'play the piano', '弹钢琴', '/pleɪ ðə piˈænəʊ/', 3, 23 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'visit grandparents', '看望祖父母', '/ˈvɪzɪt ˈɡrænpeərənts/', 3, 24 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'leaf', '叶子', '/liːf/', 4, 25 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'seed', '种子', '/siːd/', 4, 26 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'sprout', '发芽', '/spraʊt/', 4, 27 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'plant', '植物', '/plɑːnt/', 4, 28 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'honey', '蜂蜜', '/ˈhʌni/', 5, 29 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'count', '数', '/kaʊnt/', 5, 30 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'insect', '昆虫', '/ˈɪnsekt/', 5, 31 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'fight', '打架', '/faɪt/', 5, 32 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'talk', '说话', '/tɔːk/', 5, 33 FROM textbook WHERE code='PEP-G5-T2' UNION ALL
SELECT id, 'wake', '醒来', '/weɪk/', 5, 34 FROM textbook WHERE code='PEP-G5-T2';

--changeset wordapp:words-pepg6t1
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'library', '图书馆', '/ˈlaɪbrəri/', 1, 1 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'post office', '邮局', '/ˈpəʊst ɒfɪs/', 1, 2 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'hospital', '医院', '/ˈhɒspɪtl/', 1, 3 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'cinema', '电影院', '/ˈsɪnəmə/', 1, 4 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'bookstore', '书店', '/ˈbʊkstɔː/', 1, 5 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'science museum', '科学博物馆', '/ˈsaɪəns mjuˈzɪəm/', 1, 6 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'restaurant', '餐馆', '/ˈrestrɒnt/', 1, 7 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'near', '近的', '/nɪə/', 1, 8 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'next to', '与...相邻', '/nekst tə/', 1, 9 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'in front of', '在...前面', '/ɪn frʌnt əv/', 1, 10 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'behind', '在...后面', '/bɪˈhaɪnd/', 1, 11 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'turn', '转弯', '/tɜːn/', 2, 12 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'left', '左', '/left/', 2, 13 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'right', '右', '/raɪt/', 2, 14 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'straight', '直地', '/streɪt/', 2, 15 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'traffic', '交通', '/ˈtræfɪk/', 2, 16 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'traffic light', '交通灯', '/ˈtræfɪk laɪt/', 2, 17 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'by', '乘坐', '/baɪ/', 2, 18 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'subway', '地铁', '/ˈsʌbweɪ/', 2, 19 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'next week', '下周', '/nekst wiːk/', 3, 20 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'this morning', '今天早上', '/ðɪs ˈmɔːnɪŋ/', 3, 21 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'this afternoon', '今天下午', '/ðɪs ˌɑːftəˈnuːn/', 3, 22 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'this evening', '今天晚上', '/ðɪs ˈiːvnɪŋ/', 3, 23 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'tomorrow', '明天', '/təˈmɒrəʊ/', 3, 24 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'tonight', '今晚', '/təˈnaɪt/', 3, 25 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'take a trip', '去旅行', '/teɪk ə trɪp/', 3, 26 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'dictionary', '字典', '/ˈdɪkʃənri/', 4, 27 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'comic book', '连环画册', '/ˈkɒmɪk bʊk/', 4, 28 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'word book', '单词书', '/wɜːd bʊk/', 4, 29 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'postcard', '明信片', '/ˈpəʊstkɑːd/', 4, 30 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'newspaper', '报纸', '/ˈnjuːzpeɪpə/', 4, 31 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'magazine', '杂志', '/ˌmæɡəˈziːn/', 4, 32 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'hobby', '爱好', '/ˈhɒbi/', 4, 33 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'accountant', '会计', '/əˈkaʊntənt/', 5, 34 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'actor', '男演员', '/ˈæktə/', 5, 35 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'actress', '女演员', '/ˈæktrəs/', 5, 36 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'artist', '艺术家', '/ˈɑːtɪst/', 5, 37 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'singer', '歌手', '/ˈsɪŋə/', 5, 38 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'writer', '作家', '/ˈraɪtə/', 5, 39 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'TV reporter', '电视记者', '/ˌtiː viː rɪˈpɔːtə/', 5, 40 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'engineer', '工程师', '/ˌendʒɪˈnɪə/', 5, 41 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'policeman', '警察', '/pəˈliːsmən/', 5, 42 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'pianist', '钢琴家', '/ˈpɪənɪst/', 5, 43 FROM textbook WHERE code='PEP-G6-T1' UNION ALL
SELECT id, 'scientist', '科学家', '/ˈsaɪəntɪst/', 5, 44 FROM textbook WHERE code='PEP-G6-T1';

--changeset wordapp:words-pepg6t2
INSERT INTO word (textbook_id, spelling, meaning, phonetic, unit_no, sort_order)
SELECT id, 'taller', '更高的', '/ˈtɔːlə/', 1, 1 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'shorter', '更矮的', '/ˈʃɔːtə/', 1, 2 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'stronger', '更强壮的', '/ˈstrɒŋɡə/', 1, 3 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'older', '年龄更大的', '/ˈəʊldə/', 1, 4 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'younger', '更年轻的', '/ˈjʌŋɡə/', 1, 5 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'bigger', '更大的', '/ˈbɪɡə/', 1, 6 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'heavier', '更重的', '/ˈhevɪə/', 1, 7 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'thinner', '更瘦的', '/ˈθɪnə/', 1, 8 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'longer', '更长的', '/ˈlɒŋɡə/', 1, 9 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'smaller', '更小的', '/ˈsmɔːlə/', 1, 10 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'have a fever', '发烧', '/hæv ə ˈfiːvə/', 2, 11 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'have a cold', '感冒', '/hæv ə kəʊld/', 2, 12 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'have a toothache', '牙痛', '/hæv ə ˈtuːθeɪk/', 2, 13 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'have a headache', '头痛', '/hæv ə ˈhedeɪk/', 2, 14 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'have a sore throat', '喉咙痛', '/hæv ə sɔː θrəʊt/', 2, 15 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'sore', '酸痛的', '/sɔː/', 2, 16 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'sick', '生病的', '/sɪk/', 2, 17 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'angry', '生气的', '/ˈæŋɡri/', 3, 18 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'bored', '无聊的', '/bɔːd/', 3, 19 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'excited', '兴奋的', '/ɪkˈsaɪtɪd/', 3, 20 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'worried', '担心的', '/ˈwʌrid/', 3, 21 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'afraid', '害怕的', '/əˈfreɪd/', 3, 22 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'went', 'go过去式', '/went/', 4, 23 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'saw', 'see过去式', '/sɔː/', 4, 24 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'had', 'have过去式', '/hæd/', 4, 25 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'did', 'do过去式', '/dɪd/', 4, 26 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'went hiking', '去远足', '/went ˈhaɪkɪŋ/', 4, 27 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'bought', 'buy过去式', '/bɔːt/', 4, 28 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'took', 'take过去式', '/tʊk/', 4, 29 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'made', 'make过去式', '/meɪd/', 4, 30 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'ate', 'eat过去式', '/eɪt/', 5, 31 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'drank', 'drink过去式', '/dræŋk/', 5, 32 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'learned', 'learn过去式', '/lɜːnd/', 5, 33 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'heard', 'hear过去式', '/hɜːd/', 5, 34 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'got', 'get过去式', '/ɡɒt/', 5, 35 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'dancing', '跳舞', '/ˈdɑːnsɪŋ/', 5, 36 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'singing', '唱歌', '/ˈsɪŋɪŋ/', 5, 37 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'riding', '骑', '/ˈraɪdɪŋ/', 5, 38 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'swimming', '游泳', '/ˈswɪmɪŋ/', 5, 39 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'playing', '玩', '/ˈpleɪɪŋ/', 5, 40 FROM textbook WHERE code='PEP-G6-T2' UNION ALL
SELECT id, 'fishing', '钓鱼', '/ˈfɪʃɪŋ/', 5, 41 FROM textbook WHERE code='PEP-G6-T2';
